### ISSUE TITLE
Training script for Synthia 4D

### ISSUE THREAD

**Issue by ecr23xx** [chrischoy/SpatioTemporalSegmentation#2]
Could you provide training script file for synthia 4D like scannet? Thanks!

**Comment by chrischoy** [comment]
Hi, I am under some heavy workload. How soon do you need this?

**Comment by ecr23xx** [comment]
Maybe before November 1st?

**Comment by chrischoy** [comment]
Sorry for the delay. I found out that the Meteor net used a different split that is a lot easier. https://github.com/xingyul/meteornet/issues/1

I'll wrap it up as soon as possible.

**Comment by chrischoy** [comment]
https://github.com/chrischoy/SpatioTemporalSegmentation/commit/5d9e51adf74eb4947957ec29b20382abd2b4b374
