### ISSUE TITLE
module 'lib' has no attribute 'datasets'

### ISSUE THREAD

**Issue by avinashsen707** [chrischoy/SpatioTemporalSegmentation#21]
```
Traceback (most recent call last):
  File "/content/SpatioTemporalSegmentation/main.py", line 26, in <module>
    from lib.datasets import load_dataset
  File "/content/SpatioTemporalSegmentation/lib/datasets/__init__.py", line 1, in <module>
    import lib.datasets.synthia as synthia
AttributeError: module 'lib' has no attribute 'datasets'
```

**Comment by chrischoy** [comment]
I'm not following. Why would you install tensorflow 2.0?

Regardless, this is due to python not adding the current path to the python path.

Run with `python -m main`

**Comment by zaiweizhang** [comment]
Hi, I am having the same issue, and I have tried running with python -m main
I believe in the train script it's using python -m main.
It doesn't work. Would you mind providing other solutions?
