### ISSUE TITLE
[Bug] incorrect val loader during training

### ISSUE THREAD

**Issue by s9xie** [chrischoy/SpatioTemporalSegmentation#3]
https://github.com/chrischoy/SpatioTemporalSegmentation/blob/76995998b94547a1bcf0096a220dc9f737f11da8/lib/datasets/scannet.py#L83

Val is incorrectly set to trainval.txt. During training the whole trainval set will be evaluated rather than the val set.

**Comment by chrischoy** [comment]
Ah, sorry, I refactored in hurry and introduced the error in the previous commit. Thanks for submitting the issue!
 https://github.com/chrischoy/SpatioTemporalSegmentation/commit/4b1315c12994203fee8c7042c6dfc7b83cf56427#diff-76e0ee493d9758b22eeb69c88806433aL84

**Comment by s9xie** [comment]
No worries! Thanks Chris!
