### ISSUE TITLE
Possible bugs in train.py

### ISSUE THREAD

**Issue by thangvubk** [chrischoy/SpatioTemporalSegmentation#33]
Thank you for a very nice project. 
When scanning through lib/train.py, I found two possible bugs:
1. [L#78](https://github.com/chrischoy/SpatioTemporalSegmentation/blob/fc01d5b85094335c0acdc2d86b92aac1a746e0ae/lib/train.py#L78) ``coords[:, :3] += (torch.rand(3) * 100).type_as(coords)`` should be ``coords[:, 1:] += (torch.rand(3) * 100).type_as(coords)`` since first coords is the batch index
2. [L#83](https://github.com/chrischoy/SpatioTemporalSegmentation/blob/fc01d5b85094335c0acdc2d86b92aac1a746e0ae/lib/train.py#L83) ``input[:, 1:] = input[:, 1:] / 255. - 0.5`` should be ``input[:, :3] = input[:, :3] / 255. - 0.5``

**Comment by chrischoy** [comment]
Thanks for reporting the error. I've pushed the fix.
