### ISSUE TITLE
Point-level predictions from voxels

### ISSUE THREAD

**Issue by amineremache** [chrischoy/SpatioTemporalSegmentation#40]
Hello Chris,

In the paper you are mentioning that to get point-level predictions, you are propagating them from the voxels.

![image](https://user-images.githubusercontent.com/19911661/86811556-543e4200-c07e-11ea-827b-5b4f9f9cb00d.png)

And from what I understood, you need to use the argument  `--evaluate_original_pointcloud`, but as you can see: 
The "pointcloud" is not implemented.

![image](https://user-images.githubusercontent.com/19911661/86812036-d75f9800-c07e-11ea-8af1-92a63b1f301b.png)

So I thought maybe I should use the other flag, `--test_original_pointcloud`, which uses the `save_predictions` function.

![image](https://user-images.githubusercontent.com/19911661/86812259-1aba0680-c07f-11ea-9e70-a0bac25aac71.png)

But the function tries to import `OnlineVoxelizationDatasetBase` , that doesn't exist anywhere in the code ( except where it is being called )

![image](https://user-images.githubusercontent.com/19911661/86812526-666cb000-c07f-11ea-9414-96783b972fae.png)

![image](https://user-images.githubusercontent.com/19911661/86812575-76848f80-c07f-11ea-82e3-0b2d3f8642f0.png)

My question is : Am I doing things the right way ? or is there something that I am missing ? 

Thank you

**Comment by chrischoy** [comment]
Please check out https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/indoor.py#L126

**Comment by amineremache** [comment]
> Please check out https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/indoor.py#L126

The example is working, thank you.
