### ISSUE TITLE
Can you post the code for voxelize_temporal?

### ISSUE THREAD

**Issue by BestSonny** [chrischoy/SpatioTemporalSegmentation#9]
@chrischoy  Thank you very much. https://github.com/chrischoy/SpatioTemporalSegmentation/blob/master/lib/dataset.py#L348

**Comment by chrischoy** [comment]
Ah thanks for pointing this out. Let me work on in right now.

**Comment by BestSonny** [comment]
> Ah thanks for pointing this out. Let me work on in right now.

Thank you very much

**Comment by chrischoy** [comment]
It turned out that I didn't include the training scripts.

You have to download the original Synthia camera params to run this.
Let me know if you get into a trouble.

https://github.com/chrischoy/SpatioTemporalSegmentation/commit/36d67fe3319c39862d0a155978aadb0312f86a99

**Comment by BestSonny** [comment]
@chrischoy Thank you for spending your time to have a quick update. Sure, I'll let you know if having any problems.
